#------------------------------------------------------------
# Values for this lesson.
#------------------------------------------------------------

# Which carpentry is this (swc, dc, lc, or cp)?
# swc: Software Carpentry
# dc: Data Carpentry
# lc: Library Carpentry
# cp: Carpentries (to use for instructor training for instance)
# incubator: The Carpentries Incubator
# Note that you can also use a custom carpentry type. For more info,
# see the documentation: https://carpentries.github.io/sandpaper-docs/editing.html
carpentry: 'cmscat'

# Custom carpentry description
# This will be used as the alt text for the logo
carpentry_description: "CMS Common Analysis Tools Group"

# Overall title for pages.
title: "GitLab CI for CMS"

# Date the lesson was created (YYYY-MM-DD, this is empty by default)
created: ''

# Comma-separated list of keywords for the lesson
keywords: 'CMS, GitLab, CI/CD, CMSDAS, HEP'

# Life cycle stage of the lesson
# possible values: pre-alpha, alpha, beta, stable
life_cycle: 'beta'

# License of the lesson materials (recommended CC-BY 4.0)
license: 'CC-BY 4.0'

# Link to the source repository for this lesson
source: 'https://github.com/FNALLPC/cmsdas-cat-gitlab-cms'

# Default branch of your lesson
branch: 'main'

# Who to contact if there are any issues
contact: 'team@carpentries.org'

# Navigation ------------------------------------------------
#
# Use the following menu items to specify the order of
# individual pages in each dropdown section. Leave blank to
# include all pages in the folder.
#
# Example -------------
#
# episodes:
# - introduction.md
# - first-steps.md
#
# learners:
# - setup.md
#
# instructors:
# - instructor-notes.md
#
# profiles:
# - one-learner.md
# - another-learner.md

# Order of episodes in your lesson
episodes: 
- 01-introduction.md
- 02-cmsswexercise.md
# - 02-compiling.md
# - 03-vomsproxy.md
# - 04-catservices.md
# - 05-running.md
# - 07-building-image.md

# Information for Learners
learners: 
- reference.md
- setup.md

# Information for Instructors
instructors: 
# - instructor-notes.md

# Learner Profiles
profiles: 

# Customisation ---------------------------------------------
#
# This space below is where custom yaml items (e.g. pinning
# sandpaper and varnish versions) should live


